dragonwell-project/dragonwell8

.github/commit_message_template

Summary:
- Added .github/commit_message_template file
- Developers are expected to use following command to create any new Git commits
`git commit -t .github/commit_message_template`
Test Plan: only review needed
Reviewed-by: kuaiwei, sanhong
Issue: #18

[Misc] Add .github/commit_message_template

---

README.md

There is an official maintained build of Alibaba Dragonwell in Alibaba
Cloud Linux 2 (Aliyun Linux 2), so update the README file.
Signed-off-by: Caspar Zhang <caspar@linux.alibaba.com>

readme: add install instructions for Alibaba Cloud Linux 2

---

get_source_dragonwell.sh

Summary: Use github.com.cnpmjs.org as github proxy
Reviewed-by: kelthuzadx, yuleil
Issue: alibaba/dragonwell8#254

[Misc] Use github.com.cnpmjs.org as github proxy

---

get_source_dragonwell.sh

Summary: Revert github.com.cnpmjs.org as github proxy
Reviewed-by: kelthuzadx, yuleil
Issue: alibaba/dragonwell8#254

[Misc] Revert github.com.cnpmjs.org as github proxy

---

hotspot/src/share/vm/utilities/taskqueue.hpp

Summary: Make parent class ParallelTaskTerminator destructor virtual.
Test Plan: Test case
Reviewed-by:
Issue: https://github.com/alibaba/dragonwell8/issues/319

[GC] Memory leak because OWSTTaskTerminator destructor not called

---

jdk/test/com/alibaba/rcm/TestPropertyContainerImpls.java

Summary: fix jdk/test/com/alibaba/rcm/TestPropertyContainerImpls.java test run fail because of "MultiTenant only works on Linux x64 platform"
Reviewed-by: joeylee.lz, lvfei.lv
Issue: https://github.com/alibaba/dragonwell8/issues/337
CR:

[Misc] fix test TestPropertyContainerImpls.java fail

---

hotspot/src/share/vm/runtime/arguments.hpp

Summary: warning C4800: 'jboolean' : forcing value to bool 'true' or 'false'
Test Plan: ci pipelines
Reviewed-by: kelthuzadx, Accelerator1996
Issue: https://github.com/alibaba/dragonwell8/issues/330

[Misc] Fix windows build error

---

jdk/test/com/alibaba/wisp/TestWispDetailCounter.java
jdk/test/com/alibaba/wisp/io/BlockingAccept2Test.java

Summary: fix com/alibaba/wisp/TestWispDetailCounter.java and com/alibaba/wisp/io/BlockingAccept2Test.java testcase fail because of java.net.BindException: Address already in use
Issue: https://github.com/alibaba/dragonwell8/issues/358

[Misc] fix testcase TestWispDetailCounter.java

---

jdk/test/com/alibaba/wisp2/Wisp2TimerRemoveTest.java

Summary: disable wisp testcase com/alibaba/wisp2/Wisp2TimerRemoveTest.java temporarily
Issue: https://github.com/alibaba/dragonwell8/issues/360

[Misc] disable wisp testcase Wisp2TimerRemoveTest.java temporarily

---

jdk/test/jdk/jfr/event/gc/stacktrace/TestG1OldAllocationPendingStackTrace.java

Summary: fix testcase bug TestG1OldAllocationPendingStackTrace.java, which intermittently fail on linux-x64
Issue: https://github.com/alibaba/dragonwell8/issues/367

[Misc] fix testcase bug TestG1OldAllocationPendingStackTrace.java

---

jdk/test/jdk/jfr/event/oldobject/TestClassLoaderLeak.java

Summary: This test implicitly wants at least one GC cycle to happen so that ObjectSampler::oop_storage_gc_notification turns the sampled objects "old". An easy way to do this is to trim the Java heap size. 
Issue: https://github.com/alibaba/dragonwell8/issues/369

[Misc] fix testcase bug TestClassLoaderLeak.java

---

hotspot/test/runtime/8233197/Test8233197.sh

Summary: fix testcase bug hotspot/test/runtime/8233197/Test8233197.sh, which gcc not support -m64 option on linux-aarch64 platform
Issue: https://github.com/alibaba/dragonwell8/issues/373

[Misc] fix testcase bug Test8233197.sh

---

hotspot/test/runtime/8233197/Test8233197.sh
jdk/test/java/net/Inet4Address/LookUpAllAddrsTest.sh

Summary: fix testcase bug jdk/test/java/net/Inet4Address/LookUpAllAddrsTest.sh. Referring to the practice of the upstream openjdk community, such as jdk/test/java/net/InetAddress/ptr/lookup.sh, when the test condition are not met, return 0 to exit
Issue: https://github.com/alibaba/dragonwell8/issues/375

[Misc] fix testcase bug LookUpAllAddrsTest.sh

---

jdk/test/multi-tenant/test/com/alibaba/tenant/TestHierachicalTenants.java
jdk/test/multi-tenant/test/com/alibaba/tenant/TestJGroup.java

Summary: Since the TestJGroup.java test run requires a separate and clean environment, it is configured as a manual use case; Merge patch from ajdk/jdk8u/codereview/8500250 to fix testcade TestHierachicalTenants.java bug
Reviewed-by: jeffery.wsj, lvfei.lv
Issue: https://github.com/alibaba/dragonwell8/issues/361

[Misc] fix multi-tenant testcase TestHierachicalTenants.java and TestJGroup.java

---

jdk/test/com/alibaba/wisp2/yield/YieldFewNanosTest.java

Summary: disable wisp testcase com/alibaba/wisp2/yield/YieldFewNanosTest.java temporarily, which failed ro tun 2 times in a row
Issue: https://github.com/alibaba/dragonwell8/issues/378

[Misc] disable wisp testcase YieldFewNanosTest.java temporarily

---

jdk/test/ProblemList.txt
jdk/test/com/alibaba/wisp2/Wisp2TimerRemoveTest.java

Summary: disable wisp testcase com/alibaba/wisp2/CarrierAsPollerTest.java com/alibaba/wisp/ExecutionTest.java com/alibaba/wisp/IoTest.java com/alibaba/wisp/io/GlobalPollerTest.java temporarily
Issue: https://github.com/alibaba/dragonwell8/issues/371

[Misc] disable wisp testcase CarrierAsPollerTest.java ExecutionTest.java IoTest.java GlobalPollerTest.java temporarily

---

hotspot/test/jwarmup/TestCheckIfCompilationIsComplete.sh
hotspot/test/jwarmup/TestDisableMethodData.sh
hotspot/test/jwarmup/TestNotDeoptJITMethod.sh
hotspot/test/jwarmup/TestNotifyDeopt.sh
hotspot/test/jwarmup/TestTieredCompilationInRecording.sh
hotspot/test/jwarmup/issue9780156.sh

Summary: By default in ubuntu system, sh points to dash, which causes sh use case execution to report an syntax error. Relate testcase: jwarmup/TestCheckIfCompilationIsComplete.sh jwarmup/TestDisableMethodData.sh jwarmup/TestNotDeoptJITMethod.sh jwarmup/TestNotifyDeopt.sh jwarmup/TestTieredCompilationInRecording.sh jwarmup/issue9780156.sh
Reviewed-by: kuaiwei.kw, lvfei.lv
Issue: https://github.com/alibaba/dragonwell8/issues/383

[Misc] fix jwarmup/issue9780156.sh run fail on ubuntu

---

jdk/test/ProblemList.txt

Summary: disable wisp testcase com/alibaba/wisp/thread/PreemptTest.java by problemlist temporarily
Issue: https://github.com/alibaba/dragonwell8/issues/388

[Misc] disable wisp testcase PreemptTest.java by problemlist temporarily

---

hotspot/src/share/vm/runtime/coroutine.cpp
hotspot/src/share/vm/runtime/coroutine.hpp
hotspot/src/share/vm/runtime/thread.cpp
hotspot/src/share/vm/runtime/thread.hpp

Summary: Wisp unfortunately missed doing do_oop() for WispThread, which is corresponded to a Coroutine data structure. We shall add it.
Test Plan: all wisp tests
Reviewed-by: yuleil, sanhong
Issue: #189

[Wisp] Fix missing oops_do for WispThread

---

hotspot/test/multi-tenant/TestParGCAllocatorLeak.sh

Summary: By default in ubuntu system, sh points to dash, which causes sh use array to report an syntax error. Relate testcase: hotspot/test/multi-tenant/TestParGCAllocatorLeak.sh
Reviewed-by: jeffery.wsj, lvfei.lv
Issue: https://github.com/alibaba/dragonwell8/issues/408

[Misc] fix TestParGCAllocatorLeak.sh run fail on ubuntu

---

jdk/test/java/util/SplittableRandom/SplittableRandomTest.java

Summary: fix jdk/test/java/util/SplittableRandom/SplittableRandomTest.java intermittently fail, use /dev/urandom instead of /dev/random to avoid block for SecureRandom API
Reviewed-by: lvfei.lv, lei.yul
Issue: https://github.com/alibaba/dragonwell8/issues/428

[Misc] fix SplittableRandomTest.java intermittently timeout

---

jdk/test/java/security/cert/CertPathBuilder/targetConstraints/BuildEEBasicConstraints.java
jdk/test/java/security/cert/pkix/policyChanges/TestPolicy.java

Summary: fix TestPolicy.java and BuildEEBasicConstraints.java fail because of certificates expired
Reviewed-by: lvfei.lv, lei.yul
Issue: https://github.com/alibaba/dragonwell8/issues/433

[Misc] fix TestPolicy.java and BuildEEBasicConstraints.java fail because of certificates expired

---

jdk/src/share/classes/java/net/Socket.java
jdk/test/com/alibaba/wisp/io/ServerSocketConnectionTest.java

Summary: Socket.connect() in Wisp's implementation, uses nio SocketChannel's logic to prevent blocking when Socket is used. However, OpenJDK's isConnected() returns true after successfully connecting even if the socket gets closed. This will break consistency so we shall fix this.
Test Plan: newly-added ServerSocketConnectionTest.java
Reviewed-by: D-D-H
Issue: #437

[Wisp] Keep aligning Socket.isConnected() with the normal OpenJDK returning result

---

jdk/src/share/classes/java/net/ServerSocket.java
jdk/src/share/classes/java/net/Socket.java
jdk/test/com/alibaba/wisp/io/ServerSocketConnectionTest.java

Summary: Same as #438: we have another path ServerSocket.accept() to cover.
Test Plan: ServerSocketConnectionTest.java
Reviewed-by: D-D-H, yuleil
Issue: #437

[Wisp] Keep aligning Socket.isConnected() with the normal OpenJDK returning result for ServerSocket.accept()

---

jdk/src/share/classes/sun/util/resources/TimeZoneNames.java
jdk/src/share/classes/sun/util/resources/de/TimeZoneNames_de.java
jdk/src/share/classes/sun/util/resources/es/TimeZoneNames_es.java
jdk/src/share/classes/sun/util/resources/fr/TimeZoneNames_fr.java
jdk/src/share/classes/sun/util/resources/it/TimeZoneNames_it.java
jdk/src/share/classes/sun/util/resources/ja/TimeZoneNames_ja.java
jdk/src/share/classes/sun/util/resources/ko/TimeZoneNames_ko.java
jdk/src/share/classes/sun/util/resources/pt/TimeZoneNames_pt_BR.java
jdk/src/share/classes/sun/util/resources/sv/TimeZoneNames_sv.java
jdk/src/share/classes/sun/util/resources/zh/TimeZoneNames_zh_CN.java
jdk/src/share/classes/sun/util/resources/zh/TimeZoneNames_zh_TW.java

We missed this patch when merging `jdk8u322-ga`, which caused the failure of `jdk/test/java/util/TimeZone/Bug6329116.java`.
#442

[Landing] 8276536: Update TimeZoneNames files to follow the changes made by JDK-8275766

---

hotspot/src/share/vm/opto/memnode.cpp
hotspot/src/share/vm/runtime/globals_ext.hpp

Summary: A dead loop was observed in C2 optimizations. This deadloop is very rare and hard to reproduce. A conservative way is used to fix this issue. If a dead loop is detected. Just stop compiling this method at level 4.
Reviewed-by: kuaiwei.kw, yueshi.zwj
Issue: https://github.com/alibaba/dragonwell8/issues/455
Test Plan: internal tests

[JIT] Fix a deadloop in c2 compiler

---

hotspot/src/share/vm/classfile/classLoaderData.cpp
hotspot/src/share/vm/classfile/classLoaderData.hpp
hotspot/src/share/vm/gc_implementation/parNew/parCardTableModRefBS.cpp
hotspot/src/share/vm/oops/instanceKlass.cpp
hotspot/src/share/vm/prims/jvmtiRawMonitor.cpp
hotspot/src/share/vm/utilities/bitMap.inline.hpp

Summary:  this patch addes mem barriers in JVM.
Including:
8154750: Add missing OrderAccess operations to ClassLoaderData
lock-free data structures
https://bugs.openjdk.org/browse/JDK-8154750
8233073: Make BitMap accessors more memory ordering friendly
https://bugs.openjdk.org/browse/JDK-8233073
8221584: SIGSEGV in os::PlatformEvent::unpark() in
JvmtiRawMonitor::raw_exit while posting
method exit event
https://bugs.openjdk.org/browse/JDK-8221584
8166197: assert(RelaxAssert || w != Thread::current()->_MutexEvent)
failed: invariant
8164207: Checking missing load-acquire in relation to _pd_set in
dictionary.cpp
https://bugs.openjdk.org/browse/JDK-8164207
and adding a loadload barrier in CMS
Test Plan: e-commerce online tests
Reviewers: maoliang.ml, lxw263044
Issue: …

[Misc] Adding barriers on JVM

---

README.md
jdk/test/ProblemList.txt

Summary: Dragonwell has been migrated to the new org 'dragonwell-project'. We should update links to it.
Test Plan: -
Reviewed-by: D-D-H, Accelerator1996
Issue: #527

[Misc] Update dragonwell links to new org

---

jdk/src/linux/classes/com/alibaba/wisp/engine/WispConfiguration.java
jdk/src/linux/classes/com/alibaba/wisp/engine/WispEventPump.java
jdk/test/com/alibaba/wisp2/bug/TestIssue311.java

Summary: Supports different coroutines waiting on the same socket's read and write events. Solve a wisp bug triggered by okhttp.
Test Plan: TestIssue311
Reviewed-by: zhengxiaolinX, D-D-H
Issue: https://github.com/dragonwell-project/dragonwell8/issues/311

[Wisp] Separate IO poller

---

hotspot/src/share/vm/runtime/arguments.cpp
hotspot/test/gc/TestDefaultGC.sh

Summary: The same as title
Test Plan: hotspot/test/gc/TestDefaultGC.sh
Reviewed-by: kuaiwei, JoshuaZhuwj
Issue: https://github.com/alibaba/dragonwell8/issues/561

[Misc] change default gc from CMS to PS

---

hotspot/src/share/vm/classfile/sharedClassUtil.cpp
hotspot/src/share/vm/classfile/sharedClassUtil.hpp
hotspot/src/share/vm/memory/filemap.cpp
hotspot/src/share/vm/runtime/globals_ext.hpp
hotspot/src/share/vm/runtime/quickStart.cpp
hotspot/src/share/vm/runtime/quickStart.hpp
jdk/test/com/alibaba/quickstart/TestEnvClass.java
jdk/test/com/alibaba/quickstart/TestEnvVariableDump.java
jdk/test/com/alibaba/quickstart/TestEnvVariableReplay.java

Summary: If user give environment vars and use
`-Dcom.alibaba.cds.cp.reloc.envs`, cds will change the classpath by using given environment vars to transform some paths in classpath.
Test Plan: ci jtreg
jdk/test/com/alibaba/quickstart/TestEnvVariableReplay.java jdk/test/com/alibaba/quickstart/TestEnvVariableDump.java
Reviewed-by: lingjun-cg, yuleil
Issue: https://github.com/dragonwell-project/dragonwell8/issues/595

[EagerAppCDS] enable classpath change by replacing given env var

---

jdk/src/share/classes/java/lang/ClassLoader.java
jdk/test/java/lang/invoke/lambda/LogGeneratedClassesTest.java

Summary: when call definePackage, it is necessary to check the existed key in its packages and its ancestors' packages
Test Plan: jck8d Package003 in JCK-runtime-8d/tests/api/java_lang/ClassLoader/PackageTests.java
Reviewed-by: lingjun-cg, yuleil
Issue: https://github.com/dragonwell-project/dragonwell8/issues/598

[EagerAppCDS] fix bug: definePackage should check cld's parent

---

hotspot/src/share/vm/runtime/quickStart.cpp

Summary: As title. We need to convert size_t to int obviously on windows.
Test Plan: windows build
Reviewed-by: lingjun-cg, yuleil
Issue: https://github.com/dragonwell-project/dragonwell8/issues/601 CR:

[EagerAppCDS] fix build failure on windows

---

jdk/src/share/classes/java/lang/ClassLoader.java
jdk/test/java/lang/invoke/lambda/LogGeneratedClassesTest.java

Summary: Don't use lambda in ClassLoader.java since jvm may fail during initializing.
Testing: aqavit test
Reviewers: lingjun-cg, yuleil
Issue: https://github.com/dragonwell-project/dragonwell8/issues/603

[EagerAppCDS] fix bug caused by using lambda in ClassLoader.java

---

jdk/test/com/alibaba/quickstart/TestDumpWithFixedJMXPort.java

Summary: As title. The fix codes are in this project -- https://github.com/dragonwell-project/serverless-adapter-jdk8/
Testing: jdk/test/com/alibaba/quickstart/TestDumpWithFixedJMXPort.java
Reviewers: lingjun-cg, yuleil
Issue: https://github.com/dragonwell-project/dragonwell8/issues/613

[EagerAppCDS] Enhancement for support apps with fixed jmxremote port

---

jdk/test/com/alibaba/cds/TestDumpAndLoadClass.java
jdk/test/com/alibaba/cds/TestDumpAndLoadClassWithException.java
jdk/test/com/alibaba/cds/TestDumpAndLoadClassWithNullURL.java
jdk/test/com/alibaba/cds/TestDumpAndLoadClassWithWisp.java
jdk/test/com/alibaba/cds/TestDumpAndLoadNotFound.java
jdk/test/com/alibaba/cds/TestDumpAndLoadVerficationFailure.java
jdk/test/com/alibaba/cds/TestDumpListInParallel.java
jdk/test/com/alibaba/cds/TestDumpUnsupportedCheck.java
jdk/test/com/alibaba/cds/TestLoadClassFlow.java
jdk/test/com/alibaba/cds/TestRegisterClassLoader.java
jdk/test/com/alibaba/cds/TestSuppressingAppCDSErrors.java
jdk/test/com/alibaba/cds/TestWispWithAppCDS.java
jdk/test/com/alibaba/cds/appcds/TestDumpAndLoadForAppCDS.java
jdk/test/com/alibaba/cds/testClassLoaderJVMTI.sh
jdk/test/com/alibaba/cds/testDelegatingClassLoaderJVMTI.sh
jdk/test/com/alibaba/quickstart/TestAssemblyFiles.java
jdk/test/com/alibaba/quickstart/TestDeterminingTracerOrReplayer.java
jdk/test/com/alibaba/quickstart/TestDumpWithFixedJMXPort.java
jdk/test/com/alibaba/quickstart/TestEnvVariableDump.java
jdk/test/com/alibaba/quickstart/TestEnvVariableReplay.java
jdk/test/com/alibaba/quickstart/TestIntegrityCheck.java
jdk/test/com/alibaba/quickstart/TestNotifyDump.java
jdk/test/com/alibaba/quickstart/TestNotifyDumpByAPI.java
jdk/test/com/alibaba/quickstart/TestNotifyDumpByJcmd.java
jdk/test/com/alibaba/quickstart/TestParallelProcessRun.java
jdk/test/com/alibaba/quickstart/TestPrintStat.java
jdk/test/com/alibaba/quickstart/TestQuickStartOptions.java

Summary: as title
Testing: jdk/test/com/alibaba/{quickstart,cds}
Reviewers: lingjun-cg, yulei
Issue:

[EagerAppCDS] fix testcases due to upstream updates

---

jdk/test/elastic-heap/TestElasticHeapErrorCode.java
jdk/test/elastic-heap/TestElasticHeapMTSetError.java
jdk/test/elastic-heap/TestElasticHeapMXBean.java
jdk/test/elastic-heap/TestElasticHeapMXBeanException.java
jdk/test/jdk/jfr/jvm/TestClearStaleConstants.java

Summary: As title.
Testing: ci jtreg
elastic-heap/TestElasticHeapErrorCode.java
elastic-heap/TestElasticHeapMTSetError.java
elastic-heap/TestElasticHeapMXBean.java
elastic-heap/TestElasticHeapMXBeanException.java
jdk/jfr/jvm/TestClearStaleConstants.java
Reviewers: lingjun-cg, yulei
Issue: https://github.com/dragonwell-project/dragonwell8/issues/620

[GC] fix complie errors for elastic-heap and jfr testcase

---

jdk/test/jdk/jfr/event/compiler/TestHugeObjectAllocationSample.java

Summary: As title.
Testing: ci jtreg
jdk/test/jdk/jfr/event/compiler/TestHugeObjectAllocationSample.java
Reviewers: lingjun-cg, yulei
Issue: https://github.com/dragonwell-project/dragonwell8/issues/620

[JFR] fix complie errors for a jfr testcase

---

hotspot/src/share/vm/jfr/recorder/checkpoint/types/jfrTypeSet.cpp

Summary: fix the bug imported by [Backport] 8230400: Missing constant pool entry for a method in stacktrace
Testing: ci jtreg, it's not easy to write a special testcase
Reviewers: zhuoang.ddh yibo
Issue: https://github.com/dragonwell-project/dragonwell8/issues/641
CR: https://github.com/dragonwell-project/dragonwell8/pull/642

[Backport] 8261354: SIGSEGV at MethodIteratorHost

---

hotspot/src/share/vm/runtime/quickStart.cpp

Summary: as title
Testing: /test/com/alibaba/quickstart/TestEnvVariableReplay.java
Reviewers: lingjun-cg, yulei
Issue: https://github.com/dragonwell-project/dragonwell8/issues/646

[EagerAppCDS] fix bug by clearing buffer before using

---

hotspot/src/share/vm/runtime/mutex.cpp

[Backport] 8166197: assert(RelaxAssert || w != Thread::current()->_MutexEvent) failed: invariant
Summary: Add load-acquire and store-release on share variable _OnDeck to ensure Mutex work on AArch64.
Testing: No testcase becuase the frequency is occasionally when run G1 gc with high cpu usage.
Reviewers: kuaiwei, yuleil
Issue: https://github.com/dragonwell-project/dragonwell8/issues/647

[Backport] 8166197: assert(RelaxAssert || w != Thread::current()->_MutexEvent) failed: invariant

---

.github/actions/build-serverless-adapter/action.yml
.github/workflows/build-linux.yml
.github/workflows/check_pr.yml
.github/workflows/submit.yml
.github/workflows/test.yml

Summary: reduce arm runner permissions and update actions config
Testing: CI pipline
Reviewers: D-D-H, sendaoYan
Issue: https://github.com/dragonwell-project/dragonwell8/issues/651

[Misc] Reduce runner permissions

---

jdk/src/solaris/native/sun/nio/ch/rdma/Rsocket.c
jdk/src/solaris/native/sun/nio/ch/rdma/Rsocket.h

Summary: Fix compilation error in rsocket file
Testing: CI testing
Reviewers: raodao, lvfei.lv
Issue: https://github.com/dragonwell-project/dragonwell8/issues/654

[Misc] Support build with gcc 10

---

hotspot/src/share/vm/gc_implementation/parallelScavenge/psAdaptiveSizePolicy.cpp
hotspot/src/share/vm/gc_implementation/parallelScavenge/psAdaptiveSizePolicy.hpp
hotspot/src/share/vm/runtime/arguments.cpp
hotspot/src/share/vm/runtime/globals_ext.hpp

Summary: add new parallel gc option UseIOPrioritySizePolicy to early shrink heap when io wait is high.
Testing: jtreg
Reviewers: maoliang.ml, yude.lyd
Issue: https://github.com/dragonwell-project/dragonwell8/pull/661
CR: https://github.com/dragonwell-project/dragonwell8/pull/662

[GC] Add IO related size policy for Parallel GC

---

hotspot/src/share/vm/runtime/globals_ext.hpp

Summary: change type from float to uint for IOPrioritySizePolicyEdenScale to avoid build failure on aarch64
Testing: maoliang.ml, yude.lyd
Reviewers: maoliang.ml, yude.lyd
Issue: https://github.com/dragonwell-project/dragonwell8/issues/664
CR: https://github.com/dragonwell-project/dragonwell8/pull/663

[GC] Fix option type in IOPrioritySizePolicy

---

hotspot/src/share/vm/runtime/arguments.cpp
hotspot/src/share/vm/runtime/globals_ext.hpp
jdk/src/share/classes/java/math/BigDecimal.java
jdk/test/java/math/BigDecimal/StrippingTailZerosTest.java

Summary: Use binary search in zero stripping of BigDecimal.divide
Testing: jtreg
Reviewers: zhuoren.wz, JoshuaZhuwj
Issue: https://github.com/dragonwell-project/dragonwell8/issues/665

[Misc] optimize BigDecimal.divide

---

jdk/test/TEST.groups
jdk/test/security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java
jdk/test/security/infra/java/security/cert/CertPathValidator/certification/CertignaCA.java
jdk/test/security/infra/java/security/cert/CertPathValidator/certification/DTrustCA.java
jdk/test/security/infra/java/security/cert/CertPathValidator/certification/DigicertCSRootG5.java
jdk/test/security/infra/java/security/cert/CertPathValidator/certification/EmSignRootG2CA.java
jdk/test/security/infra/java/security/cert/CertPathValidator/certification/HaricaCA.java
jdk/test/security/infra/java/security/cert/CertPathValidator/certification/LuxTrustCA.java

Summary: make ca related tests manual to avoid ci failure
Testing: ci pipeline
Reviewers: lvfei, yangyi
Issue: https://github.com/dragonwell-project/dragonwell8/issues/669

[Backport] 8334441: Mark tests in jdk_security_infra group as manual

---

hotspot/src/share/vm/gc_implementation/parallelScavenge/psAdaptiveSizePolicy.cpp

Summary: use SIZE_FORMAT to avoid build failure on windows
Testing: jtreg
Reviewers: yyang, yude.lyd
Issue: https://github.com/dragonwell-project/dragonwell8/issues/672

[GC] Fix data type in IOPrioritySizePolicy

---

hotspot/src/share/vm/jfr/recorder/repository/jfrEmergencyDump.cpp

Summary: The format of snprintf expect a string, but pass an integer value in function create_emergency_chunk_path which defined in file jfrEmergencyDump.cpp.
Testing: jfr/event/gc/detailed/TestPromotionFailedEventWithParallelScavenge.java
Reviewers: sendaoYan, D-D-H
Issue: https://github.com/dragonwell-project/dragonwell8/issues/690

[JFR] Test jfr/event/gc/detailed/TestPromotionFailedEventWithParallelScavenge.java crash

---

jdk/test/TEST.ROOT

Summary: as title
Testing: jtreg test com/alibaba/wisp/timer/*
Reviewers: yuleil, lingjun-cg
Issue: https://github.com/alibaba/dragonwell8/issues/489

[Wisp] timer related testcases should not test concurrently
